import { HomeworkEntry, Item, MealMenu, Timetable } from './types';

export interface SampleDataSet {
  nurseryItems: Item[];
  elementaryItems: Item[];
  nurseryMeals: MealMenu[];
  elementaryMeals: MealMenu[];
  timetable: Timetable;
  homework: HomeworkEntry[];
}

const MARCH_SAMPLE_DATA: SampleDataSet = {
  nurseryItems: [
    { id: '2026-03-ns-1', title: '3月3日（火）体操', cat: '行事', date: '2026-03-03', memo: '〜3月の保育園行事予定', done: false, checkItems: [], mode: 'nursery' },
    { id: '2026-03-ns-2', title: '3月5日（木）リトミック参観', cat: '行事', date: '2026-03-05', memo: '〜3月の保育園行事予定', done: false, checkItems: [], mode: 'nursery' },
    { id: '2026-03-ns-3', title: '3月6日（金）ひまわり組を送る会', cat: '行事', date: '2026-03-06', memo: '〜3月の保育園行事予定', done: false, checkItems: [], mode: 'nursery' },
    { id: '2026-03-ns-4', title: '3月10日（火）卒園式予行', cat: '行事', date: '2026-03-10', memo: '〜3月の保育園行事予定', done: false, checkItems: [], mode: 'nursery' },
    { id: '2026-03-ns-5', title: '3月12日（木）英語', cat: '行事', date: '2026-03-12', memo: '〜3月の保育園行事予定', done: false, checkItems: [], mode: 'nursery' },
    { id: '2026-03-ns-6', title: '3月14日（土）卒園式', cat: '行事', date: '2026-03-14', memo: '〜3月の保育園行事予定', done: false, checkItems: [], mode: 'nursery' },
    { id: '2026-03-ns-7', title: '3月16日（月）造形ばら・ゆり', cat: '行事', date: '2026-03-16', memo: '〜3月の保育園行事予定', done: false, checkItems: [], mode: 'nursery' },
    { id: '2026-03-ns-8', title: '3月17日（火）体操', cat: '行事', date: '2026-03-17', memo: '〜3月の保育園行事予定', done: false, checkItems: [], mode: 'nursery' },
    { id: '2026-03-ns-9', title: '3月18日（水）誕生会', cat: '行事', date: '2026-03-18', memo: '〜3月の保育園行事予定', done: false, checkItems: [], mode: 'nursery' },
    { id: '2026-03-ns-10', title: '3月20日（金）春分の日', cat: '行事', date: '2026-03-20', memo: '〜3月の保育園行事予定', done: false, checkItems: [], mode: 'nursery' },
    { id: '2026-03-ns-11', title: '3月24日（火）卒園遠足', cat: '行事', date: '2026-03-24', memo: '〜3月の保育園行事予定', done: false, checkItems: [], mode: 'nursery' },
    { id: '2026-03-ns-12', title: '3月26日（木）英語', cat: '行事', date: '2026-03-26', memo: '〜3月の保育園行事予定', done: false, checkItems: [], mode: 'nursery' },
    { id: '2026-03-ns-13', title: '3月31日（火）進級式', cat: '行事', date: '2026-03-31', memo: '〜3月の保育園行事予定', done: false, checkItems: [], mode: 'nursery' },
  ],
  elementaryItems: [
    {
      id: '2026-03-el-1',
      title: '3月16日（月）行事: 給食最終日・お別れ花道',
      cat: '行事',
      date: '2026-03-16',
      memo: '時間割: 国語（自分はっけん発表会）/ 生活（お手紙オープン）/ 算数（学習のまとめ）/ 学活（お別れ花道）。',
      done: false,
      checkItems: [],
      mode: 'elementary',
    },
    {
      id: '2026-03-el-2',
      title: '3月17日（火）卒業証書授与式（臨時休業）',
      cat: '行事',
      date: '2026-03-17',
      memo: '朝自習〜4校時まで臨時休業。',
      done: false,
      checkItems: [],
      mode: 'elementary',
    },
    {
      id: '2026-03-el-3',
      title: '3月18日（水）短縮4時間（給食なし）',
      cat: 'お知らせ',
      date: '2026-03-18',
      memo: '下校 12:10。時間割: 国語（書写）/ 図工（紙けん玉）/ 図工（1年間の作品まとめ）/ 体育（持久走・ボールけり）。',
      done: false,
      checkItems: [],
      mode: 'elementary',
    },
    {
      id: '2026-03-el-4',
      title: '3月19日（木）短縮4時間（給食なし）',
      cat: 'お知らせ',
      date: '2026-03-19',
      memo: '下校 12:10。時間割: 国語（ひろがることば）/ 学活（お楽しみ会）/ 体育（スポーツ版）/ 算数（サプライズ）。',
      done: false,
      checkItems: [],
      mode: 'elementary',
    },
    {
      id: '2026-03-el-5',
      title: '3月20日（金）春分の日',
      cat: '行事',
      date: '2026-03-20',
      memo: '自然をたたえ、生物をいつくしむ日。',
      done: false,
      checkItems: [],
      mode: 'elementary',
    },
    {
      id: '2026-03-el-6',
      title: '持ち物（3月16日）',
      cat: '持ち物',
      date: '2026-03-16',
      memo: '上ばき・体そうふく・工作マット・わりばし・毛糸（1mくらい）・自分はっけんファイル。',
      done: false,
      checkItems: [],
      mode: 'elementary',
    },
    {
      id: '2026-03-el-7',
      title: '持ち物（3月18日/19日）',
      cat: '持ち物',
      date: '2026-03-18',
      memo: '18日: ファイル・教科書持ち帰り。19日: 作品バッグ持ち帰り。',
      done: false,
      checkItems: [],
      mode: 'elementary',
    },
    {
      id: '2026-03-el-8',
      title: '3月16日 連絡',
      cat: 'お知らせ',
      date: '2026-03-16',
      memo: '〜10:30 業間休み / 10:35〜11:10 3時間目 / 11:15〜11:30 そうじ / 11:35〜11:45 帰りのしたく / 11:45〜12:30 給食 / 12:30〜13:00 放送。下校 13:30。',
      done: false,
      checkItems: [],
      mode: 'elementary',
    },
    {
      id: '2026-03-el-9',
      title: '3月23日（月）短縮4時間（給食なし）',
      cat: '行事',
      date: '2026-03-23',
      memo: '時間割: 国語（ひろがることば・これまでこれから／言葉あそび 日本のことばリズム）/ 算数（もうすぐ3年生・学習のまとめ）/ 体育（校庭 10:20〜11:05 スペシャルお楽しみ会）/ 図工（11:10〜11:55 作品バッグに自分マークをかこう）。下校 12:10。',
      done: false,
      checkItems: [],
      mode: 'elementary',
    },
    {
      id: '2026-03-el-10',
      title: '3月24日（火）短縮4時間（給食なし）',
      cat: '行事',
      date: '2026-03-24',
      memo: '時間割: 学活（通知表を見て来年のめあてを立てよう）/ 生活（3年生の場所をかくにんしよう）/ 国語（連絡帳日記 1年間をふりかえろう）/ 学活（春休みの生活について）。下校 12:10。',
      done: false,
      checkItems: [],
      mode: 'elementary',
    },
    {
      id: '2026-03-el-11',
      title: '3月25日（水）修了式・離任式',
      cat: '行事',
      date: '2026-03-25',
      memo: '朝自習: 作品のまとめ、体育館移動。8:35〜 修了式、10:25〜体育館移動、10:35〜 離任式。国語: 3年生になった自分へお手紙。下校 11:30。',
      done: false,
      checkItems: [],
      mode: 'elementary',
    },
    {
      id: '2026-03-el-12',
      title: '持ち物（3月23日）',
      cat: '持ち物',
      date: '2026-03-23',
      memo: '上ばき・荷物持ち帰りのふくろ。',
      done: false,
      checkItems: [],
      mode: 'elementary',
    },
    {
      id: '2026-03-el-13',
      title: '持ち物（3月25日）',
      cat: '持ち物',
      date: '2026-03-25',
      memo: '通知表を入れるクリアケース。',
      done: false,
      checkItems: [],
      mode: 'elementary',
    },
    {
      id: '2026-03-el-14',
      title: '3月23日週 連絡',
      cat: 'お知らせ',
      date: '2026-03-23',
      memo: '今週は週プロのみ配布。あと3日で令和7年度の2年3組は「解散（かいさん）」になります。「えがおのリレー」「ありがとうのクラス」をいつもより多く見られるといいですね。',
      done: false,
      checkItems: [],
      mode: 'elementary',
    },
  ],
  nurseryMeals: [
    { date: '2026-03-02', lunch: 'のりたまごはん／鶏の照り焼き／切り干し大根の和え物／たまねぎとじゃがいものみそ汁', snack: 'りんご' },
    { date: '2026-03-03', lunch: 'お花のいろどりむすび／鮭のオーロラソース／ブロッコリーのおかか和え／菜の花と油麩のすまし汁', snack: 'ももゼリー' },
    { date: '2026-03-04', lunch: '具沢山ちゃんぽんめん／大学いも／のりとしらすのサラダ／ソフール いちご味', snack: '' },
    { date: '2026-03-05', lunch: '納豆ご飯（きりざい）／さばのごまねぎソース／茎わかめの炒り煮／はくさいとなすのみそ汁', snack: 'バナナ' },
    { date: '2026-03-06', lunch: 'マカロニグラタン／コーンとレタスのサラダ／ポトフスープ', snack: 'みかん' },
    { date: '2026-03-07', lunch: 'ねぎ塩にゅうめん／和風じゃがベー／青りんごゼリー', snack: '' },
    { date: '2026-03-09', lunch: '白飯／かじきのフライ／なっとうサラダ／せりと豚肉のみそ汁', snack: 'バナナ' },
    { date: '2026-03-10', lunch: 'タコライス／ウィンナーとアスパラのソテー／アーサー汁／チチヤスヨーグルト', snack: '' },
    { date: '2026-03-11', lunch: 'バターロール／スパニッシュオムレツ／トマトとキャベツのサラダ／ゴロゴロ野菜のミルクスープ', snack: 'バナナ' },
    { date: '2026-03-12', lunch: 'たらこスパゲッティ／スティックサラダ／肉団子スープ／青りんごゼリー', snack: '' },
    { date: '2026-03-13', lunch: 'チキンカレーライス／もやしとささみのナムル／かき玉汁', snack: 'バナナ' },
    { date: '2026-03-16', lunch: 'のりたまごはん／鶏の照り焼き／切り干し大根の和え物／たまねぎとじゃがいものみそ汁', snack: 'りんご' },
    { date: '2026-03-17', lunch: 'お花のいろどりむすび／鮭のオーロラソース／ブロッコリーのおかか和え／菜の花と油麩のすまし汁', snack: 'ももゼリー' },
    { date: '2026-03-18', lunch: 'ハンバーガー／しましまハムチーズ／春セロリの鶏がらスープ／ピーチゼリー', snack: '' },
    { date: '2026-03-19', lunch: '納豆ご飯（きりざい）／さばのごまねぎソース／茎わかめの炒り煮／はくさいとなすのみそ汁', snack: 'バナナ' },
    { date: '2026-03-23', lunch: '白飯／かじきのフライ／なっとうサラダ／せりと豚肉のみそ汁', snack: 'バナナ' },
    { date: '2026-03-24', lunch: '麻婆豆腐丼／せんまいの3色ナムル／ビーフンスープ', snack: 'りんご' },
    { date: '2026-03-25', lunch: 'バターロール／スパニッシュオムレツ／トマトとキャベツのサラダ／ゴロゴロ野菜のミルクスープ', snack: 'バナナ' },
    { date: '2026-03-26', lunch: 'たらこスパゲッティ／スティックサラダ／肉団子スープ／青りんごゼリー', snack: '' },
    { date: '2026-03-27', lunch: 'チキンカレーライス／もやしとささみのナムル／かき玉汁', snack: 'バナナ' },
    { date: '2026-03-28', lunch: '五目豚肉うどん／鶏肉とさつまいもの洋風ソテー／チチヤスヨーグルト', snack: '' },
    { date: '2026-03-30', lunch: 'ミートソーススパゲティー／ウィンナーとアスパラのソテー／アーサー汁／チチヤスヨーグルト', snack: '' },
    { date: '2026-03-31', lunch: 'バターロール／ハンバーグ／マカロニサラダ／コーンスープ', snack: 'みかん' },
  ],
  elementaryMeals: [
    { date: '2026-03-02', lunch: 'ごはん／ぎゅうにゅう／ししゃものあおのりあげ／はるさめサラダ／マーボーどうふ／しらぬいゼリー' },
    { date: '2026-03-03', lunch: 'むぎごはん／ぎゅうにゅう／おはなハンバーグ／ポテトサラダ（だいずマヨネーズ）／なのはないりすましじる／ひなあられ' },
    { date: '2026-03-04', lunch: 'しょくパン／ぎゅうにゅう／いかのスパイシーあげ／りんごドレッシングサラダ／はるやさいのクリームに／チョコレートクリーム' },
    { date: '2026-03-05', lunch: 'ごはん／ぎゅうにゅう／とりのからあげ／キャベツのあえもの／ABCスープ／さつまいもいりこざかな' },
    { date: '2026-03-06', lunch: 'ぎゅうにゅう／ぶたキムチどん／わかめとはるさめのたまごスープ／キャラメルポテト' },
    { date: '2026-03-09', lunch: 'ぎゅうにゅう／たけのこいりとりそぼろどん／わふうワンタンスープ／いちごともものゼリーポンチ' },
    { date: '2026-03-10', lunch: 'ごはん／ぎゅうにゅう／さばのたつたあげ／なっとうあえ／はるやさいのみそしる' },
    { date: '2026-03-11', lunch: 'ぎゅうにゅう／とんこつしょうゆラーメン／わふうとうふごまサラダ／やきプリンタルト' },
    { date: '2026-03-12', lunch: 'ぎゅうにゅう／カレーライス／グリーンサラダ／ココアまめ' },
    { date: '2026-03-13', lunch: 'シュガーあげパン／ぎゅうにゅう／チリ・コン・カン／キャベツのおかかサラダ／いちごヨーグルト' },
    { date: '2026-03-16', lunch: 'せきはん／ごましお／ぎゅうにゅう／チキンカツ／なのはなとコーンのサラダ／すましじる／おいわいクレープ', memo: '給食最終日' },
    { date: '2026-03-17', lunch: '臨時休業（給食なし）', memo: '卒業証書授与式' },
    { date: '2026-03-18', lunch: '給食なし', memo: '短縮4時間' },
    { date: '2026-03-19', lunch: '給食なし', memo: '短縮4時間' },
    { date: '2026-03-20', lunch: '祝日（春分の日）', memo: '学校休業日' },
  ],
  timetable: {
    mon: [
      { subject: '国語', note: 'ひろがることば／これまでこれから／言葉あそび 日本のことばリズム' },
      { subject: '算数', note: 'もうすぐ3年生／学習のまとめ' },
      { subject: '体育', note: '10:20〜11:05（校庭）スペシャルお楽しみ会' },
      { subject: '図工', note: '11:10〜11:55 作品バッグに自分マークをかこう' },
    ],
    tue: [
      { subject: '学活', note: '通知表を見て来年のめあてを立てよう' },
      { subject: '生活', note: '3年生の場所をかくにんしよう' },
      { subject: '国語', note: '連絡帳日記／1年間をふりかえろう' },
      { subject: '学活', note: '春休みの生活について' },
    ],
    wed: [
      { subject: '国語', note: '3年生になった自分へお手紙' },
      { subject: '国語', note: '春休み' },
      { subject: '行事', note: '8:35〜 修了式' },
      { subject: '行事', note: '10:35〜 離任式' },
    ],
    thu: [],
    fri: [],
  },
  homework: [
    { id: '2026-03-hw-1', date: '2026-03-16', subject: '国語', description: '自分はっけんファイルを読み返す', done: false },
    { id: '2026-03-hw-2', date: '2026-03-16', subject: '算数', description: '2年生のまとめプリント', done: true },
    { id: '2026-03-hw-3', date: '2026-03-18', subject: '国語', description: '2年生で学習した漢字の復習', done: false },
    { id: '2026-03-hw-4', date: '2026-03-19', subject: '生活', description: '1年間の思い出を絵日記に書く', done: false },
  ],
};

const APRIL_SAMPLE_DATA: SampleDataSet = {
  nurseryItems: [
    { id: '2026-04-ns-1', title: '4月2日（木）慣らし保育スタート', cat: 'お知らせ', date: '2026-04-02', memo: '新年度の持ち物と送迎時間を再確認してください。', done: false, checkItems: [], mode: 'nursery' },
    { id: '2026-04-ns-2', title: '4月6日（月）入園・進級を祝う会', cat: '行事', date: '2026-04-06', memo: '記名した上履きとカラー帽子を持参。', done: false, checkItems: [], mode: 'nursery' },
    { id: '2026-04-ns-3', title: '4月9日（木）英語あそび', cat: '行事', date: '2026-04-09', memo: '通常保育で実施します。', done: false, checkItems: [], mode: 'nursery' },
    { id: '2026-04-ns-4', title: '4月15日（水）身体測定', cat: '行事', date: '2026-04-15', memo: '脱ぎ着しやすい服で登園してください。', done: false, checkItems: [], mode: 'nursery' },
    { id: '2026-04-ns-5', title: '4月22日（水）誕生会', cat: '行事', date: '2026-04-22', memo: '4月生まれのお友だちをお祝いします。', done: false, checkItems: [], mode: 'nursery' },
    { id: '2026-04-ns-6', title: '4月30日（木）こいのぼり制作持ち帰り', cat: '持ち物', date: '2026-04-30', memo: '大きめの持ち帰り袋をご準備ください。', done: false, checkItems: [], mode: 'nursery' },
  ],
  elementaryItems: [
    { id: '2026-04-el-1', title: '4月6日（月）始業式', cat: '行事', date: '2026-04-06', memo: '下校 11:30。新しい連絡帳と筆記用具を持参。', done: false, checkItems: [], mode: 'elementary' },
    { id: '2026-04-el-2', title: '4月7日（火）入学式のため短縮3時間', cat: 'お知らせ', date: '2026-04-07', memo: '2〜6年生は給食なし、下校 11:45。', done: false, checkItems: [], mode: 'elementary' },
    { id: '2026-04-el-3', title: '4月8日（水）給食開始', cat: '行事', date: '2026-04-08', memo: '白衣・マスク・ランチョンマットを持参。', done: false, checkItems: [], mode: 'elementary' },
    { id: '2026-04-el-4', title: '4月10日（金）保護者会資料を配布', cat: '提出物', date: '2026-04-10', memo: '家庭環境調査票と緊急連絡カードを4月13日までに提出。', done: false, checkItems: [], mode: 'elementary' },
    { id: '2026-04-el-5', title: '4月17日（金）避難訓練', cat: '行事', date: '2026-04-17', memo: '防災頭巾を学校に置いているか確認。', done: false, checkItems: [], mode: 'elementary' },
    { id: '2026-04-el-6', title: '4月24日（金）1年生を迎える会', cat: '行事', date: '2026-04-24', memo: '学年ごとの出し物を体育館で行います。', done: false, checkItems: [], mode: 'elementary' },
  ],
  nurseryMeals: [
    { date: '2026-04-01', lunch: 'わかめご飯／鶏のから揚げ／春キャベツのサラダ／豆腐のみそ汁', snack: 'オレンジ' },
    { date: '2026-04-06', lunch: 'ハヤシライス／コールスローサラダ／りんごゼリー', snack: 'バナナ' },
    { date: '2026-04-10', lunch: '鮭ごはん／肉じゃが／小松菜のおひたし／なめこのみそ汁', snack: '牛乳かん' },
    { date: '2026-04-15', lunch: 'たぬきうどん／ちくわの磯辺揚げ／ブロッコリーサラダ', snack: 'いちご' },
    { date: '2026-04-22', lunch: 'タコライス／かぼちゃサラダ／コンソメスープ', snack: 'ヨーグルト' },
    { date: '2026-04-30', lunch: 'ロールパン／ハンバーグ／マカロニサラダ／コーンスープ', snack: 'みかん' },
  ],
  elementaryMeals: [
    { date: '2026-04-06', lunch: '給食なし', memo: '始業式' },
    { date: '2026-04-07', lunch: '給食なし', memo: '入学式準備のため短縮' },
    { date: '2026-04-08', lunch: 'ポークカレー／海藻サラダ／牛乳', memo: '新年度最初の給食' },
    { date: '2026-04-09', lunch: 'ごはん／白身魚フライ／磯香和え／みそ汁', memo: '通常給食' },
    { date: '2026-04-10', lunch: 'ミートソーススパゲティ／ツナサラダ／牛乳', memo: '通常給食' },
  ],
  timetable: {
    mon: [
      { subject: '学活', note: '新学期のめあて' },
      { subject: '国語', note: '自己紹介カード' },
      { subject: '算数', note: 'かけ算のきほん' },
      { subject: '生活', note: '春見つけ' },
    ],
    tue: [
      { subject: '国語', note: '音読' },
      { subject: '算数', note: '九九の復習' },
      { subject: '体育', note: '整列と準備運動' },
      { subject: '学活', note: '係決め' },
    ],
    wed: [
      { subject: '国語', note: '漢字の書き順' },
      { subject: '生活', note: '校内たんけん' },
      { subject: '図工', note: '春の色さがし' },
      { subject: '音楽', note: '校歌' },
    ],
    thu: [
      { subject: '算数', note: 'たし算とひき算' },
      { subject: '国語', note: '日記' },
      { subject: '体育', note: '50m走' },
      { subject: '道徳', note: 'あいさつ' },
    ],
    fri: [
      { subject: '生活', note: '学級のやくそく' },
      { subject: '国語', note: '本のしょうかい' },
      { subject: '図工', note: '自分の顔を描こう' },
      { subject: '学活', note: '1週間のふりかえり' },
    ],
  },
  homework: [
    { id: '2026-04-hw-1', date: '2026-04-08', subject: '国語', description: '教科書 p.10-13 を音読', done: false },
    { id: '2026-04-hw-2', date: '2026-04-09', subject: '算数', description: '計算ドリル p.2-3', done: false },
    { id: '2026-04-hw-3', date: '2026-04-10', subject: '生活', description: '春見つけカードを1枚書く', done: false },
  ],
};

const SAMPLE_DATA_BY_MONTH: Record<string, SampleDataSet> = {
  '2026-03': MARCH_SAMPLE_DATA,
  '2026-04': APRIL_SAMPLE_DATA,
};

export function getSampleMonthKey(baseDate = new Date()): string {
  const year = baseDate.getFullYear();
  const month = String(baseDate.getMonth() + 1).padStart(2, '0');
  return `${year}-${month}`;
}

export function getSampleDataForMonth(monthKey: string): SampleDataSet | null {
  return SAMPLE_DATA_BY_MONTH[monthKey] ?? null;
}
